# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy source and build
COPY . .
RUN npm run build

# Stage 2: Runtime
FROM node:lts-alpine
WORKDIR /app

# Copy package and production modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules

# Copy built artifacts
COPY --from=builder /app/build ./build

# Set environment
ENV NODE_ENV=production

# Expose no ports (stdio only)
ENTRYPOINT ["node", "build/index.js"]
